version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  product_service:
    build: ./ecommerce/product_service
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    volumes:
      - ./ecommerce/product_service/staticfiles:/app/staticfiles
      - ./ecommerce/product_service/media:/app/media
    networks:
      - app-network

  user_service:
    build: ./ecommerce/user_service
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    volumes:
      - ./ecommerce/user_service/staticfiles:/app/user_staticfiles
      - ./ecommerce/user_service/media:/app/user_media
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./ecommerce/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ecommerce/product_service/staticfiles:/app/staticfiles
      - ./ecommerce/user_service/staticfiles:/app/user_staticfiles
      - ./ecommerce/product_service/media:/app/media
      - ./ecommerce/user_service/media:/app/user_media
    depends_on:
      - product_service
      - user_service
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: